version: "3.9"
services:
  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - kotlin
      - flask

  kotlin:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - FRONTEND_URL=http://react:3000
      - FLASK_URL=http://flask:5000
    command: ./gradlew run
    volumes:
      - ./api:/app/api

  flask:
    build:
      context: ./ai
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python3 base.py
    volumes:
      - ./ai:/app
