version: "3.9"
services:
  react:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    volumes:
      - ./frontend:/app
    depends_on:
      - kotlin
      - flask

  kotlin:
    build:
      context: ./api
    ports:
      - "8080:8080"
    command: ./gradlew run
    volumes:
      - ./api:/app/api

  flask:
    build:
      context: ./ai
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python3 base.py
    volumes:
      - ./ai:/app
